// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: fastbit.proto
#ifndef GRPC_fastbit_2eproto__INCLUDED
#define GRPC_fastbit_2eproto__INCLUDED

#include "fastbit.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace profastbit {

class dump_fastbit GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status dumptofast(::grpc::ClientContext* context, const ::profastbit::prodata& request, ::profastbit::datareply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profastbit::datareply>> Asyncdumptofast(::grpc::ClientContext* context, const ::profastbit::prodata& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::profastbit::datareply>>(AsyncdumptofastRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::profastbit::datareply>* AsyncdumptofastRaw(::grpc::ClientContext* context, const ::profastbit::prodata& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status dumptofast(::grpc::ClientContext* context, const ::profastbit::prodata& request, ::profastbit::datareply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profastbit::datareply>> Asyncdumptofast(::grpc::ClientContext* context, const ::profastbit::prodata& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::profastbit::datareply>>(AsyncdumptofastRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::profastbit::datareply>* AsyncdumptofastRaw(::grpc::ClientContext* context, const ::profastbit::prodata& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_dumptofast_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status dumptofast(::grpc::ServerContext* context, const ::profastbit::prodata* request, ::profastbit::datareply* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    std::unique_ptr< ::grpc::RpcService> service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void Requestdumptofast(::grpc::ServerContext* context, ::profastbit::prodata* request, ::grpc::ServerAsyncResponseWriter< ::profastbit::datareply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace profastbit


#endif  // GRPC_fastbit_2eproto__INCLUDED
